[package]
name = "cryptopals-rust"
version = "0.1.0"
authors = ["carl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
base64 = "0.13"
